sudo: required
services:
    - docker

before_install:
    - docker build -t ivanpilot/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run ivanpilot/react-test npm test -- --coverage

after_success:
    - docker build -t ivanpilot/client ./client
    - docker build -t ivanpilot/nginx ./nginx
    - docker build -t ivanpilot/server ./server
    - docker build -t ivanpilot/worker ./worker

    # This is a set of command for Travis to be able to login programmatically inside docker hub so that we can then push our build image to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take our images and push them to docker hub
    - docker push ivanpilot/client
    - docker push ivanpilot/nginx
    - docker push ivanpilot/server
    - docker push ivanpilot/worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: fibonacci
    env: Fibonacci-env
    bucket_name: elasticbeanstalk-eu-west-2-660931516180
    bucket_path: fibonacci
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
